globals:
  repoURL: https://github.com/lukas-pastva/kt-eks-gitops.git
  cluster: kt-ops-eks-1
appProjects:
  - namespace: app-of-apps-namespaces
    doNotCreateNamespace: true
    applications:
      - name: app-of-apps-namespaces
        path: internal/app-of-apps-namespaces
        valueFiles: $values/cluster-kt-ops-eks-1/applications.yaml
  - namespace: argo-cd
    applications:
      - name: argocd
        path: external/argo/argo-cd/9.4.0/argo-cd

  - namespace: web-wordpress
    applications:
      - name: web-wordpress
        path: external/bitnami/wordpress/25.0.4
        
  - namespace: cert-manager
    applications:
      - name: cert-manager
        path: external/cert-manager/cert-manager/1.19.3/cert-manager

  - namespace: ingress-nginx
    applications:
      - name: ingress-nginx
        path: external/ingress-nginx/ingress-nginx/4.14.3/ingress-nginx

  - namespace: aws-load-balancer-controller
    applications:
      - name: aws-load-balancer-controller
        path: external/aws/aws-load-balancer-controller/3.0.0/aws-load-balancer-controller

  - namespace: cluster-autoscaler
    applications:
      - name: cluster-autoscaler
        path: external/kubernetes/cluster-autoscaler/9.55.0/cluster-autoscaler

  - namespace: external-dns
    applications:
      - name: external-dns
        path: external/bitnami/external-dns/9.0.3/external-dns

  - namespace: metrics-server
    applications:
      - name: metrics-server
        path: external/bitnami/metrics-server/7.4.12/metrics-server
